package it.nextworks.nfvmano.libs.osmanfvo.nslcm.interfaces.enums;

/**
 * REF IFA 013 v2.3.1 - 7.3.5
 * 
 * @author nextworks
 *
 */
public enum NsUpdateType {

	ADD_VNF,
	REMOVE_VNF,
	INSTANTIATE_VNF,
	CHANGE_VNF_DF,
	OPERATE_VNF,
	MODIFY_VNF_INFORMATION,
	MODIFY_VNF_CONFIG,
	CHANGE_EXT_VNF_CONNECTIVITY,
	ADD_SAP,
	REMOVE_SAP,
	ADD_NESTED_NS,
	REMOVE_NESTED_NS,
	ASSOC_NEW_NSD_VERSION,
	MOVE_VNF,
	ADD_VNFFG,
	REMOVE_VNFFG,
	UPDATE_VNFFG,
	CHANGE_NS_DF
	
}
